### ISSUE TITLE
LuckyPerms not working on any new NeoForge Versions above 21.4.10

### ISSUE THREAD

**Issue by pandasonic-collective** [LuckPerms/LuckPerms#4042]
### Description

LuckyPerms will work on NeoForge 21.4.10 just fine, but about 15-20 of the other mods I'm using require higher versions than 21.4.10. The highest min being 21.4.94.

I've removed all other mods and just have LuckPerms and I'm still getting this on version above 21.4.10. I have not tried every very to see which one it's breaks on, but I at least nee 21.4.94. I am currently using 21.4.110.

### Reproduction Steps

install NeoForge Server 21.4.110
install LuckyPerm 5.4.156 on Server
Run Server

### Expected Behaviour

to not crash? lol 

### Server Details

NeoForge 21.4.110

### LuckPerms Version

5.4.156

### Logs and Configs

This is the crash log

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2025-03-09 20:36:09
Description: Mod loading failures have occurred; consult the issue messages for more details

net.neoforged.neoforge.logging.CrashReportExtender$ModLoadingCrashException: Mod loading has failed


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?] {}
-- Mod loading issue for: luckperms --
Details:
        Caused by 0: java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/AddReloadListenerEvent
                at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
                at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?] {}
                at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) ~[?:?] {}
                at java.base/java.lang.Class.getMethods(Class.java:2185) ~[?:?] {}
                at me.lucko.luckperms.neoforge.util.NeoForgeEventBusFacade.register(NeoForgeEventBusFacade.java:64) ~[?:?] {}
                at me.lucko.luckperms.neoforge.LPNeoForgeBootstrap.registerListeners(LPNeoForgeBootstrap.java:146) ~[?:?] {}
                at me.lucko.luckperms.neoforge.LPNeoForgePlugin.registerEarlyListeners(LPNeoForgePlugin.java:93) ~[?:?] {}
                at me.lucko.luckperms.neoforge.LPNeoForgeBootstrap.onLoad(LPNeoForgeBootstrap.java:161) ~[?:?] {}
                at TRANSFORMER/luckperms@5.4.156/me.lucko.luckperms.neoforge.loader.NeoForgeLoaderPlugin.onCommonSetup(NeoForgeLoaderPlugin.java:71) ~[LuckPerms-NeoForge-5.4.156.jar%23144!/:5.4.156] {re:classloading}
                at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2374!/:?] {}
                at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2374!/:?] {}
                at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2374!/:?] {}
                at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158) ~[loader-6.0.11.jar%2371!/:6.0] {}
                at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.lambda$dispatchParallelEvent$4(ModLoader.java:172) ~[loader-6.0.11.jar%2371!/:6.0] {}
                at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-6.0.11.jar%2371!/:6.0] {}
                at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
                at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
                at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
                at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

        Mod file: /D:/Minecraft/NeoForge/21.4.110-beta/mods/LuckPerms-NeoForge-5.4.156.jar
        Failure message: LuckPerms (luckperms) encountered an error while dispatching the net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent event
                java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/AddReloadListenerEvent
        Mod version: 5.4.156
        Mod issues URL: https://github.com/LuckPerms/LuckPerms/issues
        Exception message: java.lang.ClassNotFoundException: net.neoforged.neoforge.event.AddReloadListenerEvent
Stacktrace:
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?] {}
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?] {}
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) ~[?:?] {}
        at java.base/java.lang.Class.getMethods(Class.java:2185) ~[?:?] {}
        at me.lucko.luckperms.neoforge.util.NeoForgeEventBusFacade.register(NeoForgeEventBusFacade.java:64) ~[?:?] {}
        at me.lucko.luckperms.neoforge.LPNeoForgeBootstrap.registerListeners(LPNeoForgeBootstrap.java:146) ~[?:?] {}
        at me.lucko.luckperms.neoforge.LPNeoForgePlugin.registerEarlyListeners(LPNeoForgePlugin.java:93) ~[?:?] {}
        at me.lucko.luckperms.neoforge.LPNeoForgeBootstrap.onLoad(LPNeoForgeBootstrap.java:161) ~[?:?] {}
        at TRANSFORMER/luckperms@5.4.156/me.lucko.luckperms.neoforge.loader.NeoForgeLoaderPlugin.onCommonSetup(NeoForgeLoaderPlugin.java:71) ~[LuckPerms-NeoForge-5.4.156.jar%23144!/:5.4.156] {re:classloading}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2374!/:?] {}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2374!/:?] {}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2374!/:?] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.lambda$dispatchParallelEvent$4(ModLoader.java:172) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}


-- System Details --
Details:
        Minecraft Version: 1.21.4
        Minecraft Version ID: 1.21.4
        Operating System: Windows 11 (amd64) version 10.0
        Java Version: 21.0.3, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 1166500840 bytes (1112 MiB) / 1308622848 bytes (1248 MiB) up to 31675383808 bytes (30208 MiB)
        CPUs: 24
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 9 5900X 12-Core Processor
        Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
        Microarchitecture: Zen 3
        Frequency (GHz): 3.69
        Number of physical packages: 1
        Number of physical CPUs: 12
        Number of logical CPUs: 24
        Graphics card #0 name: NVIDIA GeForce RTX 4090
        Graphics card #0 vendor: NVIDIA
        Graphics card #0 VRAM (MiB): 24564.00
        Graphics card #0 deviceId: VideoController1
        Graphics card #0 versionInfo: 32.0.15.7260
        Memory slot #0 capacity (MiB): 32768.00
        Memory slot #0 clockSpeed (GHz): 2.67
        Memory slot #0 type: DDR4
        Memory slot #1 capacity (MiB): 32768.00
        Memory slot #1 clockSpeed (GHz): 2.67
        Memory slot #1 type: DDR4
        Memory slot #2 capacity (MiB): 32768.00
        Memory slot #2 clockSpeed (GHz): 2.67
        Memory slot #2 type: DDR4
        Memory slot #3 capacity (MiB): 32768.00
        Memory slot #3 clockSpeed (GHz): 2.67
        Memory slot #3 type: DDR4
        Virtual memory max (MiB): 150439.53
        Virtual memory used (MiB): 54895.82
        Swap memory total (MiB): 19456.00
        Swap memory used (MiB): 92.81
        Space in storage for jna.tmpdir (MiB): <path not set>
        Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
        Space in storage for io.netty.native.workdir (MiB): <path not set>
        Space in storage for java.io.tmpdir (MiB): available: 299170.16, total: 1906904.00
        Space in storage for workdir (MiB): available: 524529.06, total: 1907712.00
        JVM Flags: 0 total;
        ModLauncher: 11.0.4+main.d2e20e43
        ModLauncher launch target: neoforgeserver
        ModLauncher services:
                sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE
                loader-6.0.11.jar slf4jfixer PLUGINSERVICE
                loader-6.0.11.jar runtime_enum_extender PLUGINSERVICE
                at-modlauncher-11.0.1.jar accesstransformer PLUGINSERVICE
                loader-6.0.11.jar runtimedistcleaner PLUGINSERVICE
                modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE
                modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE
        FML Language Providers:
                javafml@6.0
                lowcodefml@6.0
                minecraft@6.0
        Mod List:
                LuckPerms-NeoForge-5.4.156.jar                    |LuckPerms                     |luckperms
        |5.4.156             |Manifest: NOSIGNATURE
                server-1.21.4-20241203.161809-srg.jar             |Minecraft                     |minecraft
        |1.21.4              |Manifest: NOSIGNATURE
                neoforge-21.4.110-beta-universal.jar              |NeoForge                      |neoforge
        |21.4.110-beta       |Manifest: NOSIGNATURE
        Crash Report UUID: 3ae7fbae-3896-4a30-acbf-641bd7b66fd7
        FML: 6.0.11
        NeoForge: 21.4.110-beta
[20:36:09] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - LuckPerms (luckperms) encountered an error while dispatching the net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent event
          java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/AddReloadListenerEvent

        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.ModLoader.dispatchParallelEvent(ModLoader.java:171) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at TRANSFORMER/neoforge@21.4.110-beta/net.neoforged.neoforge.internal.CommonModLoader.load(CommonModLoader.java:72) ~[neoforge-21.4.110-beta-universal.jar%23143!/:?] {re:classloading}
        at TRANSFORMER/neoforge@21.4.110-beta/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:35) ~[neoforge-21.4.110-beta-universal.jar%23143!/:?] {re:classloading}
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.Main.main(Main.java:128) ~[server-1.21.4-20241203.161809-srg.jar%23142!/:?] {re:classloading}
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:128) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:124) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.loading.targets.NeoForgeServerLaunchHandler.runService(NeoForgeServerLaunchHandler.java:39) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/fml_loader@6.0.11/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:114) ~[loader-6.0.11.jar%2371!/:6.0] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2376!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2376!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2376!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2376!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2376!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2376!/:?] {}
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2376!/:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}

```

**Comment by Gameking1happy** [comment]
could be duplicate of/related to #4039?

**Comment by Gameking1happy** [comment]
could be duplicate of/related to #4039?

**Comment by pandasonic-collective** [comment]
Maybe, but this happens when the server is trying to start up. It just won't.

**Comment by Raul-Paiva** [comment]
Yha, it doesnt seems to be the same problem > Maybe, but this happens when the server is trying to start up. It just won't.

**Comment by Raul-Paiva** [comment]
Yha, it doesnt seems to be the same problem > Maybe, but this happens when the server is trying to start up. It just won't.

**Comment by pandasonic-collective** [comment]
Newest version of LuckyPerms is working for 21.4.123 now. Cheers

**Comment by jblemee** [comment]
Sorry but no published version are working on stable neoForge  (for instance: 21.4.135). Neither v5.4.150 nor v5.4.150.

The "patched" commit : https://github.com/LuckPerms/LuckPerms/commit/7744913df2e8e2ad1670fd3374c47c80143fcb64 also introduce minecraft 1.21.5 dependency :/

I've made a patched version that works on MC 1.21.4 and neoforge 21.4.x stable versions here: https://github.com/jblemee/LuckPerms/releases/tag/v1.21.4
