### ISSUE TITLE
YAML storage type not working on 5.4.5 for Fabric 1.18.1

### ISSUE THREAD

**Issue by braunly** [LuckPerms/LuckPerms#3325]
### Description

Looks like server doesn't have snakeyaml library

### Reproduction Steps

- Install Fabric server
- Install LuckPerms
- Change `storage-method` config option to `yaml` or `yaml-combined`
- Start server

### Expected Behaviour

LuckPerms starts without error and all command works

### Server Details

Minecraft 1.18.1
fabricloader 0.13.1
fabric 0.46.4+1.18

### LuckPerms Version

v5.4.5

### Logs and Configs

https://gist.github.com/braunly/93fdaa5d7f74025926f62fe4fcb4f62b

**Comment by ZeromaniacMc** [comment]
The error 'java.lang.NoClassDefFoundError' is an indicator that a dependency may not have been loaded/downloaded properly. Ofc I could be wrong, but usually the golden measure to fix this is to do the following in order:

- turn off server
- remove only(!) the `libs folder` which can be found inside your luckperms folder
- turn server back on and try again

The libs folder itself only contains stuff lp needs to work, however there is nothing inside it about your setup, so no worries about your data here. Would be cool if you could try this and see if that, as it usually does, fixes it or not and report back.
Cheers

**Comment by braunly** [comment]
@ZeromaniacMc, thank you, but LP didn't redownload snakeyaml library
Same error

**Comment by lucko** [comment]
Should be sorted by ^ - thanks for reporting :)
