### ISSUE TITLE
PandaSpigot 1.8.8 Problem with locale() since v5.5.67

### ISSUE THREAD

**Issue by Jan1598** [LuckPerms/LuckPerms#4295]
### Description

LuckPerms don't work with PandaSpigot 1.8.8 since LuckPerms v5.5.67

Stacktrace:
```
[22:18:55 ERROR]: [LuckPerms] Exception whilst executing command: []
java.lang.NoSuchMethodError: 'java.util.Locale org.bukkit.entity.Player.locale()'
        at me.lucko.luckperms.bukkit.BukkitSenderFactory$PaperBridgeBukkitSenderFactory.sendMessage0(BukkitSenderFactory.java:126) ~[luckperms-jarinjar5578866238349177881.jar.tmp:?]
        at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:77) ~[luckperms-jarinjar5578866238349177881.jar.tmp:?]
        at me.lucko.luckperms.bukkit.BukkitSenderFactory$PaperBridgeBukkitSenderFactory.sendMessage(BukkitSenderFactory.java:114) ~[luckperms-jarinjar5578866238349177881.jar.tmp:?]
        at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:93) ~[luckperms-jarinjar5578866238349177881.jar.tmp:?]
        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:241) [luckperms-jarinjar5578866238349177881.jar.tmp:?]
        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$0(CommandManager.java:193) [luckperms-jarinjar5578866238349177881.jar.tmp:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:1474) [?:?]
```

Issue:
```
/**
     * Sender factory that uses native Paper adventure support to send messages.
     */
    private static class PaperBridgeBukkitSenderFactory extends BukkitSenderFactory {
        private final PaperAdventureBridge bridge;

        public PaperBridgeBukkitSenderFactory(LPBukkitPlugin plugin, PaperAdventureBridge bridge) {
            super(plugin);
            this.bridge = bridge;
        }

        @Override
        protected void sendMessage0(CommandSender sender, Component message) {
            Locale locale = null;
            if (sender instanceof Player) {
                locale = ((Player) sender).locale(); <-- This method doesn't exists in Minecraft 1.8.8
            }
            Component rendered = TranslationManager.render(message, locale);
            this.bridge.sendMessage(sender, rendered);
        }
    }
```

### Reproduction Steps

Join a Server or use /lp on a PandaSpigot 1.8.8 Server

### Expected Behaviour

LuckPerms works as expected and throw no errors

### Server Details

git-PandaSpigot-217 (MC: 1.8.8)

### LuckPerms Version

v5.5.71

**Comment by lucko** [comment]
Please could you check to see if it's fixed in v5.5.71? :)

**Comment by Jan1598** [comment]
No, I'm afraid the problem is still there. I've also tried version 5.5.73.

**Comment by lucko** [comment]
Ok thanks for checking - should be fixed by the above commit
