### ISSUE TITLE
Webeditor not work in 1.8.8

### ISSUE THREAD

**Issue by Jan1598** [LuckPerms/LuckPerms#4301]
### Description

The webeditor with /lp editor not work in 1.8.8

### Reproduction Steps

When execute the command /lp editor in PandaSpigot 1.8.8 the following error occurs.

`
[13:31:40 INFO]: xyz issued server command: /lp editor
[13:31:40 WARN]: java.lang.NoSuchMethodError: 'void com.google.gson.JsonArray.<init>(int)'
[13:31:40 WARN]:        at me.lucko.luckperms.common.node.utils.NodeJsonSerializer.serializeNodes(NodeJsonSerializer.java:85)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.formPermissionHolder(WebEditorRequest.java:187)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.lambda$createJsonPayload$1(WebEditorRequest.java:158)
[13:31:40 WARN]:        at java.base/java.util.Map.forEach(Map.java:733)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.lambda$createJsonPayload$0(WebEditorRequest.java:157)
[13:31:40 WARN]:        at me.lucko.luckperms.common.util.gson.JArray.consume(JArray.java:79)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createJsonPayload(WebEditorRequest.java:156)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.generate(WebEditorRequest.java:149)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.create(WebEditorSession.java:60)
[13:31:40 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:289)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$0(CommandManager.java:193)
[13:31:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
[13:31:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[13:31:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[13:31:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1474)
`

### Expected Behaviour

A link to the webeditor is generated

### Server Details

git-PandaSpigot-218

### LuckPerms Version

v5.5.76

### Logs and Configs

`
[13:31:40 INFO]: xyz issued server command: /lp editor
[13:31:40 WARN]: java.lang.NoSuchMethodError: 'void com.google.gson.JsonArray.<init>(int)'
[13:31:40 WARN]:        at me.lucko.luckperms.common.node.utils.NodeJsonSerializer.serializeNodes(NodeJsonSerializer.java:85)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.formPermissionHolder(WebEditorRequest.java:187)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.lambda$createJsonPayload$1(WebEditorRequest.java:158)
[13:31:40 WARN]:        at java.base/java.util.Map.forEach(Map.java:733)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.lambda$createJsonPayload$0(WebEditorRequest.java:157)
[13:31:40 WARN]:        at me.lucko.luckperms.common.util.gson.JArray.consume(JArray.java:79)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.createJsonPayload(WebEditorRequest.java:156)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorRequest.generate(WebEditorRequest.java:149)
[13:31:40 WARN]:        at me.lucko.luckperms.common.webeditor.WebEditorSession.create(WebEditorSession.java:60)
[13:31:40 WARN]:        at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:110)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:56)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.abstraction.SingleCommand.execute(SingleCommand.java:48)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.execute(CommandManager.java:289)
[13:31:40 WARN]:        at me.lucko.luckperms.common.command.CommandManager.lambda$executeCommand$0(CommandManager.java:193)
[13:31:40 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1825)
[13:31:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
[13:31:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
[13:31:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1474)
`
